server:
  port: 8183
  servlet:
    context-path: /elastic-query-web-client

spring:
  thymeleaf:
    cache: false # disable cache during development

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client'
            client-secret: '7c8603b1-f78a-448d-a3bf-6fd670477d52'
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8189/auth/realms/microservices_realm

elastic-query-web-client-service-config:
  webclient:
    connection-timeout-ms: 10000
    read-timeout-ms: 30000
    write-timeout-ms: 30000
    max-in-memory-size: 10MB
    base-url: http://elastic-query-service/elastic-query/documents
  query-by-text:
    method: POST
    url: /get-document-by-value

user-config:
    username: user
    password: password
    roles: USER
