server:
  port: 8182
  servlet:
    context-path: /elastic-query

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8189/auth/realms/microservices_realm
          jwt-set-uri: http://localhost:8189/auth/realms/microservices_realm/protocol/openid-connect/certs

elastic-config:
  index-name: news-index
  connection-url: http://localhost:9200
  connection-timeout-ms: 5000
  socket-timeout-ms: 30000
  is-repository: true

elastic-query-config:
  field: text

user-config:
    username: user
    password: password
    roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  path-to-ignore: /api-docs/**